apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  # Replicas managed by HPA if enabled, else defaults to minReplicas or a fixed value.
  {{- if not .Values.backend.hpa.enabled }}
  replicas: {{ .Values.backend.hpa.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: flask-backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.db.database | quote }}
            - name: POSTGRES_HOST
              value: "db"
            - name: POSTGRES_PORT
              value: {{ .Values.db.port | quote }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              name: http-backend
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http-backend
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http-backend
            initialDelaySeconds: 10
            periodSeconds: 5
