apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http-backend
      name: http-backend
  selector:
    app: backend
  type: ClusterIP
