apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
    - port: {{ .Values.db.port }}
      targetPort: postgres
      name: postgres
  selector:
    app: db
  type: ClusterIP
