apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: {{ .Values.frontend.serviceType }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http-frontend
      protocol: TCP
      name: http-frontend
      {{- if eq .Values.frontend.serviceType "NodePort" }}
      nodePort: {{ .Values.frontend.nodePort }}
      {{- end }}
  selector:
    app: frontend
